language: ruby
rvm:
 - 2.2.1
 - 2.2.2
 - 2.2.3
 - 2.2.4
 - 2.3.0
 - 2.4.0-dev


notifications:      
  email: true

sudo: false
before_install: gem install bundler 
install:
  - bundle install --binstubs
  - ./bin/rake init_service 

