language: ruby
rvm:
 - 2.3.0
 - 2.3.1
 - 2.1.4

notifications:      
  email: true

sudo: false
before_install: gem install bundler 
install:
  - bundle install --binstubs
  - ./bin/rake init_service 

