language: ruby
rvm:
 - 2.2.5
 - 2.3.0
 - 2.4.0-dev


notifications:      
  email: false

sudo: false
before_install: gem install bundler 
install:
  - bundle install --binstubs
  - ./bin/rake init_service env=test
  - ./bin/rake db:create RACK_ENV=test
  - ./bin/rake db:migrate RACK_ENV=test
  - ./bin/rake test


